apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/nginx-ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true